controller:
  publishService:
    enabled: true # boolean; needed for external-dns & ingress status

  admissionWebhooks:
    enabled: false

  # No hostPort when using a LoadBalancer
  hostPort:
    enabled: false

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    # If you want to fix the IP (optional), pick one from 10.168.217.180-186:
    # loadBalancerIP: 10.168.217.180

  # Optional: common nginx settings (safe defaults)
  config:
    use-forwarded-headers: "true"
    proxy-body-size: "64m"
