apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guacamole-k8tre-tls
  namespace: jupyterhub
spec:
  secretName: guacamole-k8tre-tls
  privateKey:
    rotationPolicy: Always
  commonName: guacamole.k3s.rds.uhs.nhs.uk
  dnsNames:
    - guacamole.k3s.rds.uhs.nhs.uk
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
