apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    version: 4.2.0
    releaseName: jupyterhub
    namespace: jupyterhub
    valuesFile: values.yaml

  - name: guacamole
    repo: https://www.manicstreetpreacher.co.uk/helm-guacamole/
    version: 0.1.2
    releaseName: guacamole
    namespace: jupyterhub
    valuesFile: guacamole.yaml

  - name: generic-webservice
    repo: https://www.manicstreetpreacher.co.uk/helm-generic-webservice/
    version: 0.1.5
    releaseName: guacamolehandler
    namespace: jupyterhub
    valuesFile: guacamolehandler.yaml

resources:
  - ../../base
  - certificate-guacamole.yaml
  - guacamole-json-secret.yaml
  - jupyterhub-secret.yaml
  - netpol-singleuser.yaml
  # - netpol_singleuser_world.yaml

patches:
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: jupyter-k8tre-tls

configMapGenerator:
  - name: jupyterhub-extraconfig
    files:
      # Kustomize will create a ConfigMap with the contents of this file
      - jupyterhub_extraconfig.py
