apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
    - 10.168.217.180-10.168.217.186 # This range should be adjusted to your network configuration
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
spec:
  ipAddressPools:
    - default-pool
