# This is an ArgoCD Application manifest that serves as a parent application
# for managing multiple child applications. It is designed to be used with
# the ApplicationSet controller, which allows for dynamic generation of
# applications based on a set of parameters or templates.
# This manifest is part of a GitOps workflow, where the desired state of
# applications is defined in Git repositories.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps # Name of the application
  namespace: argocd # The namespace where ArgoCD is installed
spec:
  # Use the default project for this application
  project: default # ToDo: Consider creating a dedicated project for better organization

  # Source configuration defines where to find the application manifests
  source:
    # The Git repository containing all application definitions
    repoURL: https://github.com/paulschmeida/k8tre.git
    # The branch or tag to use - typically the main branch
    # Create a copy of this tile and change this to a feature branch for development
    # Use kubectl apply -k root-app-of-apps.yaml to deploy the application in your development environment
    targetRevision: main
    # The directory within the repository containing ApplicationSet definitions
    path: appsets
    kustomize:
      commonLabels:
        app.kubernetes.io/managed-by: argocd
      commonAnnotations:
        app.kubernetes.io/part-of: k8tre
      patches:
        - target:
            kind: ApplicationSet
          patch: |-
            - op: replace
              path: /spec/generators/0/matrix/generators/0/git/repoURL
              value: https://github.com/paulschmeida/k8tre.git
            - op: replace
              path: /spec/template/spec/source/repoURL
              value: https://github.com/paulschmeida/k8tre.git
            - op: replace
              path: /spec/generators/0/matrix/generators/0/git/revision
              value: main
            - op: replace
              path: /spec/template/spec/source/targetRevision
              value: main

  # Destination defines where to deploy the manifests
  destination:
    # Target the same cluster where ArgoCD is running (in-cluster deployment)
    # This is for the root application only.
    # Child applications will be deployed to their respective clusters.
    server: https://kubernetes.default.svc
    # Deploy resources to the ArgoCD namespace
    namespace: argocd

  # Sync policy controls how ArgoCD manages this application
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Automatically create namespaces if they don't exist
    automated:
      prune: true # Automatically delete resources that are no longer defined in Git
      selfHeal: true # Automatically sync when drift is detected between Git and cluster state
  info:
    - name: K8TRE App of Apps
      value: "https://github.com/paulschmeida/k8tre"
    - name: K8TRE Documentation
      value: "https://k8tre.github.io/k8tre/"
